export const SAVE_SALE_REQUEST = "SAVE_SALE_REQUEST";
export const FETCH_SALE_REQUEST = "FETCH_SALE_REQUEST";
export const UPDATE_SALE_REQUEST = "UPDATE_SALE_REQUEST";
export const DELETE_SALE_REQUEST = "DELETE_SALE_REQUEST";
export const SALE_SUCCESS = "SALE_SUCCESS";
export const SALE_FAILURE = "SALE_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";
